### ISSUE TITLE
ImportError: cannot import name 'cpu'

### ISSUE THREAD

**Issue by dylanqyuan** [zhanghang1989/PyTorch-Encoding#325]
Hi,

dependency:
pytorch 1.4.0,
CUDA 10.2
Pytorch_encoding master branch

the following code is run on single GPU( GeForce RTX 2080, 8GB)：

python -m scripts.prepare_ade20k

Traceback (most recent call last):
  File "/home/qyuan/anaconda3/envs/pytorch_encoding_interpreter/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/qyuan/anaconda3/envs/pytorch_encoding_interpreter/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/qyuan/PycharmProjects/pytorch_encoding/PyTorch-Encoding/scripts/prepare_ade20k.py", line 6, in <module>
    from encoding.utils import download, mkdir
  File "/home/qyuan/PycharmProjects/pytorch_encoding/PyTorch-Encoding/encoding/__init__.py", line 13, in <module>
    from . import nn, functions, parallel, utils, models, datasets, transforms
  File "/home/qyuan/PycharmProjects/pytorch_encoding/PyTorch-Encoding/encoding/nn/__init__.py", line 12, in <module>
    from .encoding import *
  File "/home/qyuan/PycharmProjects/pytorch_encoding/PyTorch-Encoding/encoding/nn/encoding.py", line 18, in <module>
    from ..functions import scaled_l2, aggregate, pairwise_cosine
  File "/home/qyuan/PycharmProjects/pytorch_encoding/PyTorch-Encoding/encoding/functions/__init__.py", line 2, in <module>
    from .encoding import *
  File "/home/qyuan/PycharmProjects/pytorch_encoding/PyTorch-Encoding/encoding/functions/encoding.py", line 15, in <module>
    from encoding import cpu

ImportError: cannot import name 'cpu'

I have read all the issues related to it, but the issue is still there,could you please give me some suggestions? thanks for your time!

**Comment by zhanghang1989** [comment]
Could you install the newest version by following the instruction at http://hangzh.s3.amazonaws.com/encoding/docs/321/notes/compile.html

If still have trouble, please try the docker option https://hangzhang.org/PyTorch-Encoding/notes/compile.html#using-docker

**Comment by EldorIbragimov** [comment]
Hi dylanqyuan, error is simple, you just need to change all the .py files in the folder "functions"
It is mentioned in your error: File "/home/qyuan/PycharmProjects/pytorch_encoding/PyTorch-Encoding/encoding/functions/encoding.py", line 15, in
from encoding import cpu
you should change it like below:
from encoding import cpu ==  from encoding.lib import cpu
from encoding import gpu == from encoding.lib import gpu

**Comment by zhanghang1989** [comment]
That's not the correct way to do it. Please do:

```
pip uninstall -y torch-encoding
pip install git+https://github.com/zhanghang1989/PyTorch-Encoding/
```

**Comment by dylanqyuan** [comment]
> 
> 
> Hi dylanqyuan, error is simple, you just need to change all the .py files in the folder "functions"
> It is mentioned in your error: File "/home/qyuan/PycharmProjects/pytorch_encoding/PyTorch-Encoding/encoding/functions/encoding.py", line 15, in
> from encoding import cpu
> you should change it like below:
> from encoding import cpu == from encoding.lib import cpu
> from encoding import gpu == from encoding.lib import gpu
> 
> I hope, it helps

Thanks for your useful and detailed suggestions! My error has been solved, I really appreciate with that!

**Comment by weiyi1991** [comment]
> Hi,
> 
> dependency:
> pytorch 1.4.0,
> CUDA 10.2
> Pytorch_encoding master branch
> 
> the following code is run on single GPU( GeForce RTX 2080, 8GB)：
> 
> python -m scripts.prepare_ade20k
> 
> Traceback (most recent call last):
> File "/home/qyuan/anaconda3/envs/pytorch_encoding_interpreter/lib/python3.6/runpy.py", line 193, in _run_module_as_main
> "**main**", mod_spec)
> File "/home/qyuan/anaconda3/envs/pytorch_encoding_interpreter/lib/python3.6/runpy.py", line 85, in _run_code
> exec(code, run_globals)
> File "/home/qyuan/PycharmProjects/pytorch_encoding/PyTorch-Encoding/scripts/prepare_ade20k.py", line 6, in
> from encoding.utils import download, mkdir
> File "/home/qyuan/PycharmProjects/pytorch_encoding/PyTorch-Encoding/encoding/**init**.py", line 13, in
> from . import nn, functions, parallel, utils, models, datasets, transforms
> File "/home/qyuan/PycharmProjects/pytorch_encoding/PyTorch-Encoding/encoding/nn/**init**.py", line 12, in
> from .encoding import *
> File "/home/qyuan/PycharmProjects/pytorch_encoding/PyTorch-Encoding/encoding/nn/encoding.py", line 18, in
> from ..functions import scaled_l2, aggregate, pairwise_cosine
> File "/home/qyuan/PycharmProjects/pytorch_encoding/PyTorch-Encoding/encoding/functions/**init**.py", line 2, in
> from .encoding import *
> File "/home/qyuan/PycharmProjects/pytorch_encoding/PyTorch-Encoding/encoding/functions/encoding.py", line 15, in
> from encoding import cpu
> 
> ImportError: cannot import name 'cpu'
> 
> I have read all the issues related to it, but the issue is still there,could you please give me some suggestions? thanks for your time!

I think the error is due to the bug of new version. I got the same error when compile the latest v1.2.2 version. But everything works fine on tags/v1.2.1 . Please use
`git checkout tags/v1.2.1`
to switch to the stable version first.
I find in v1.2.2, `encoding/lib/__init__.py` is missed, while exists in v1.2.1, which may be the cause of the error.

**Comment by dylanqyuan** [comment]
> 
> 
> > Hi,
> > dependency:
> > pytorch 1.4.0,
> > CUDA 10.2
> > Pytorch_encoding master branch
> > the following code is run on single GPU( GeForce RTX 2080, 8GB)：
> > python -m scripts.prepare_ade20k
> > Traceback (most recent call last):
> > File "/home/qyuan/anaconda3/envs/pytorch_encoding_interpreter/lib/python3.6/runpy.py", line 193, in _run_module_as_main
> > "**main**", mod_spec)
> > File "/home/qyuan/anaconda3/envs/pytorch_encoding_interpreter/lib/python3.6/runpy.py", line 85, in _run_code
> > exec(code, run_globals)
> > File "/home/qyuan/PycharmProjects/pytorch_encoding/PyTorch-Encoding/scripts/prepare_ade20k.py", line 6, in
> > from encoding.utils import download, mkdir
> > File "/home/qyuan/PycharmProjects/pytorch_encoding/PyTorch-Encoding/encoding/**init**.py", line 13, in
> > from . import nn, functions, parallel, utils, models, datasets, transforms
> > File "/home/qyuan/PycharmProjects/pytorch_encoding/PyTorch-Encoding/encoding/nn/**init**.py", line 12, in
> > from .encoding import *
> > File "/home/qyuan/PycharmProjects/pytorch_encoding/PyTorch-Encoding/encoding/nn/encoding.py", line 18, in
> > from ..functions import scaled_l2, aggregate, pairwise_cosine
> > File "/home/qyuan/PycharmProjects/pytorch_encoding/PyTorch-Encoding/encoding/functions/**init**.py", line 2, in
> > from .encoding import *
> > File "/home/qyuan/PycharmProjects/pytorch_encoding/PyTorch-Encoding/encoding/functions/encoding.py", line 15, in
> > from encoding import cpu
> > ImportError: cannot import name 'cpu'
> > I have read all the issues related to it, but the issue is still there,could you please give me some suggestions? thanks for your time!
> 
> I think the error is due to the bug of new version. I got the same error when compile the latest v1.2.2 version. But everything works fine on tags/v1.2.1 . Please use
> `git checkout tags/v1.2.1`
> to switch to the stable version first.
> I find in v1.2.2, `encoding/lib/__init__.py` is missed, while exists in v1.2.1, which may be the cause of the error.

The bug has solved,thanks for you useful advice!

Byt the way, I find that my compiler feels confusing when run `import encoding` in folder "Pytorch-encoding". 
My compiler has no idea where to import encoding Module: 
from `./encoding,` 
or from` /home/user/anaconda3/envs/pytorch-encoding/lib/python3.6/site-packages/torch_encoding-1.2.2b20200904-py3.6-linux-x86_64.egg/`
